### ISSUE TITLE
Any progress / sketches you can share

### ISSUE THREAD

**Issue by ezcGman** [cnrd/yeelock#2]
Hey there,

I found this repo in the home assistant community. It sounded link you made some progress using an ESP32!? So can you successfully lock/unlock a Yeelock with it?
Could you maybe share the sketch/code for your ESP32 then?

Thanks and greetings,

Andy!

**Comment by cnrd** [comment]
Unfortunately no, I haven't had any luck on this.

**Comment by ezcGman** [comment]
Bummer :( Thx for the reply though!

**Comment by jawadaq82** [comment]
We are able to control the Yeelock Bluetooth lock and we have created our own android app for this.

Please get back to me by email if interested our services.
